[tool.poetry]
name = "dsutil"
version = "0.19.3"
description = "A utils Python package for data scientists."
authors = ["Benjamin Du <longendu@yahoo.com>"]

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = ">=3.6"
dateparser = ">=0.7.1"
pandas = ">=0.22.0"
loguru = ">=0.3.2"
toml = ">=0.10.0"
pylint = ">=2.4.0"
yapf = ">=0.28.0"
PyPDF2 = ">=1.26.0"
requests = ">=2.20.0"
tqdm = ">=4.40.0"
opencv-python = ">=4.0.0.0"
pillow = ">=7.0.0"
GitPython = ">=3.0.0"

[tool.poetry.dev-dependencies]
pytest = ">=3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
