name: Create Pull Request
on:
  push:
    branches:
      - dev
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin master:master
          git reset --soft origin/master
      - name: Create pull request from dev to master
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge dev into master
          branch: dev
          base: master