name: Create Pull Request
on:
  push:
    branches:
      - dev
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pr_dev_master
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge dev into master
          branch: master