name: Test Code on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_code:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          #- macOS-latest
        python-version: 
          #- 3.6
          - 3.7
          - 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip3 install -U git+https://github.com/dclong/xinstall@master
        xinstall pt -ic
        ~/.poetry/bin/poetry env use python3
        ~/.poetry/bin/poetry install
    - name: Test with pytest
      run: |
        ~/.poetry/bin/poetry run pytest
